### PR TITLE
doc: update readme

### PR DESCRIPTION
**Pull request by pauldelucia**
## Issue being fixed or feature implemented

Fix some formatting and grammar.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by pauldelucia** [comment]
The formatting errors are in files I didn't even touch?

**Comment by QuantumExplorer** [comment]
@pauldelucia could you remerge master into your branch?

**Comment by pauldelucia** [comment]
@QuantumExplorer done

**Comment by QuantumExplorer** [comment]
@pauldelucia again

**Pull request merged**
